# Replace these version tags with the specific commit SHAs for each action
name: Running Solidity Unit Tests
on: [push]

jobs:
  run_sol_contracts_job:
    runs-on: ubuntu-latest
    name: A job to run solidity unit tests on github actions CI
    steps:
      - name: Checkout
        uses: actions/checkout@<full-commit-sha>
      - name: Environment Setup
        uses: actions/setup-node@<full-commit-sha>
        with:
          node-version: 20.0.0
      - name: Run SUT Action
        uses: ethereumremix/sol-test@<full-commit-sha>
        with:
          test-path: 'apps/remix-ide/contracts/tests'
          compiler-version: '0.8.15'
